version: '2'
services:
    orderbook-app:
        image: orderbook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://orderbook-mysql:3306/orderbook?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    orderbook-mysql:
        extends:
            file: mysql.yml
            service: orderbook-mysql
